### ISSUE TITLE
Improve withFilter's error object

### ISSUE THREAD

**Issue by cbowns** [troystribling/SimpleFutures#2]
When doing error handling in `onFailure`, the error returned from `withFilter` is very difficult to differentiate from other `error`s which may be passed in. I have an idea for a small improvement which would help out clients.

**Comment by troystribling** [comment]
I have made changes to error handling in the latest release. throw can now be used to create errors and a mapError is now provided to change the error value.

**Comment by cbowns** [comment]
Gotcha, cool! I've handed off the project which used SimpleFutures to someone else, so I'm gonna close this out. Thanks again for creating this project!
